---
title: "mixture_beta"
output: html_document
author: Masayuki Sakai
date: 2018/05/23
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Two beta distribution
二つのベータ分布からのサンプルを混ぜたデータを生成する

```{r generate sample }
beta_params = data.frame(x1=c(2, 10), x2=c(10,1.4))

set.seed(777)
x1 <- rbeta(n=1000, shape1 = beta_params[1,1], shape2 = beta_params[2,1])
x2 <- rbeta(n=500, shape1 = beta_params[1,2], shape2 = beta_params[2,2])

par(mfrow=c(1,2))
hist(x1, col="#b569694D", xlim=c(0,1), probability = TRUE)
curve(dbeta(x,
            shape1 = beta_params[1,1],
            shape2 = beta_params[2,1]),
      ylab="", col="#b56969", add=TRUE, lwd=2)


hist(x2, col="#22264b4D", xlim=c(0,1), probability = TRUE)


curve(dbeta(x,
            shape1 = beta_params[1,2],
            shape2 = beta_params[2,2]),
      ylab="", col="#22264b", add=TRUE, lwd=2)

```

```{r curve of pdf}
curve(dbeta(x,
            shape1 = beta_params[1,1],
            shape2 = beta_params[2,1]),
      ylab="", col="#b56969", lwd=2, ylim=c(0, 5.5))

curve(dbeta(x,
            shape1 = beta_params[1,2],
            shape2 = beta_params[2,2]),
      ylab="", col="#22264b", add=TRUE, lwd=2)

```


```{r overlaid hist}
X <- data.frame(x=c(x1,x2), label=c(rep("a", length(x1)), label=rep("b", length(x2))))
hist(X$x, xlim=c(0,1), breaks = 10)
```

```{r message=FALSE, warning=FALSE}
library(betareg)
set.seed(777)
res <- betamix(x~1|1, data=X, k=1:3)
```

```{r}
res$flexmix
```

```{r}
m <- res
mu <- plogis(coef(m)[,1])
phi <- exp(coef(m)[,2])

a <- mu * phi
b <- (1 - mu) * phi

cl <- clusters(m)

## separate histograms for both clusters
hist(subset(X, cl == 1)$x, breaks = 0:25/25, freq = FALSE,
  col = hcl(0, 50, 80), main = "", xlab = "y", ylim = c(0, 9))

hist(subset(X, cl == 2)$x, breaks = 0:25/25, freq = FALSE,
  col = hcl(240, 50, 80), main = "", xlab = "y", ylim = c(0, 9), add = TRUE)

## lines for fitted densities
ys <- seq(0, 1, by = 0.01)
lines(ys, dbeta(ys, shape1 = a[1], shape2 = b[1]),
  col = hcl(0, 80, 50), lwd = 2)
lines(ys, dbeta(ys, shape1 = a[2], shape2 = b[2]),
  col = hcl(240, 80, 50), lwd = 2)

## lines for corresponding means
abline(v = mu[1], col = hcl(0, 80, 50), lty = 2, lwd = 2)
abline(v = mu[2], col = hcl(240, 80, 50), lty = 2, lwd = 2)
```


```{r}
curve(dbeta(x,
            shape1 = beta_params[1,1],
            shape2 = beta_params[2,1]),
      ylab="", col="#b56969", lwd=2, ylim=c(0, 5.5))

curve(dbeta(x,
            shape1 = beta_params[1,2],
            shape2 = beta_params[2,2]),
      ylab="", col="#22264b", add=TRUE, lwd=2)


ys <- seq(0, 1, by = 0.01)
lines(ys, dbeta(ys, shape1 = a[1], shape2 = b[1]),
  col = hcl(0, 80, 50), lwd = 2)
lines(ys, dbeta(ys, shape1 = a[2], shape2 = b[2]),
  col = hcl(240, 80, 50), lwd = 2)

```

